### ISSUE TITLE
WSL: Python module "requests" not found error

### ISSUE THREAD

**Issue by C4pt41nNRex** [epacke/logstash-pipeline-tester#111]
Hi everyone,

After cloning the repository, I tried to run `sudo docker-compose build` from my WSL Ubuntu machine. However, I got the error:

```
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 18, in <module>
    import docker
  File "/usr/lib/python3/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/lib/python3/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

Also, I tried it from my virtual environment. However, the outcome is the same. Then, I thought maybe adding the path:

```
export PYTHONPATH=/home/cptrex/.local/lib/python3.11/site-packages
```

And then the following lines in the docker-compose.yml file after line 9:

```
environment:
      PYTHONPATH: "/home/cptrex/.local/lib/python3.11/site-packages"
```

Same result, unsuccessful. 

Do you know how to solve this issue?

Thank you in advance.

Best regards,

Cpt. Rex

**Comment by epacke** [comment]
Hi Rex!
This looks like a client docker-compose problem (not the code or manifests). Try re-installing docker on your machine and make sure that you run the latest version of docker. On my lab machine I use Docker Desktop with WSL2.

Try setting up Docker like this SO article describes?
https://stackoverflow.com/questions/61592709/docker-not-running-on-ubuntu-wsl-due-to-error-cannot-connect-to-the-docker-daemo

I'll close this ticket since it does not seem to be a code problem but feel free to comment with the results. I'll read and reply.

**Comment by C4pt41nNRex** [comment]
Hi Patrick,

Thank you for your reply.

You were right, my apologies to open a not valid issue here.

If I can help, it was solved just updating docker-compose:

```
sudo pip install --upgrade docker-compose
```

Now it's all good. Just to say that I really like this tool.

Have a nice day.

Best regards

Cpt. Rex

**Comment by epacke** [comment]
No problem. Glad you like it!
